name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Revisión de Estilo de Código
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Revisar archivos JavaScript
        run: npm run lint:js

  test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    name: Ejecución de Pruebas
    needs: lint
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test
      - name: Notificar en Slack (Error en Despliegue)
        if: always()
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{job.status}}
      
  deploy:
    runs-on: ubuntu-latest
    name: Despliegue en GitHub Pages
    needs: test
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Crear directorio de despliegue
        run: mkdir -p gh-pages

      - name: Copiar archivos de docs a gh-pages
        run: cp -r docs/* gh-pages/

      - name: Desplegar en GitHub Pages
        if: needs.test.result == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./gh-pages
