name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Revisión de Estilo de Código
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Revisar archivos JavaScript
        run: npm run lint:js

  test:
    runs-on: ubuntu-latest
    name: Ejecución de Pruebas
    needs: lint
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    name: Despliegue en GitHub Pages
    needs: test
    if: needs.test.result == 'success'
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Crear directorio de despliegue
        run: mkdir -p gh-pages

      - name: Copiar archivos de docs a gh-pages
        run: cp -r docs/* gh-pages/

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./gh-pages

  notify_success:
    runs-on: ubuntu-latest
    needs: deploy
    if: needs.deploy.result == 'success'
    steps:
      - name: Notificar en Slack (Despliegue Exitoso)
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Pipeline CI/CD para la rama ${{ github.ref }} desplegada exitosamente."}' ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: failure()
    steps:
      - name: Notificar en Slack (Error en Despliegue)
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Pipeline CI/CD para la rama ${{ github.ref }} falló durante el despliegue."}' ${{ secrets.SLACK_WEBHOOK_URL }}
