name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Set up de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalacion de dependencias
        run: npm install

      - name: Iniciar ESLint
        run: npx eslint docs/**/*.js

      - name: Run tests
        run: npm test

      - name: Crear directorio de despliegue
        if: success()
        run: mkdir -p gh-pages

      - name: Copiar archivos de docs a gh-pages
        if: success()
        run: cp -r docs/* gh-pages/

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./gh-pages

      - name: Notificaciones en Slack (Error en Despliegue)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI/CD Pipeline for branch ${{ github.ref }} failed during deployment."}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notificaciones en Slack (Despliegue Exitoso)
        if: success() && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI/CD Pipeline for branch ${{ github.ref }} deployed successfully."}' ${{ secrets.SLACK_WEBHOOK_URL }}
