name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - DEV
  pull_request:
    branches:
      - main
      - DEV

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Revisión de Estilo de Código
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Revisar archivos JavaScript
        run: npm run lint:js

  test:
    runs-on: ubuntu-latest
    name: Ejecución de Pruebas
    needs: lint
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    name: Despliegue en GitHub Pages
    needs: test
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v2

      - name: Crear directorio de despliegue
        run: mkdir -p gh-pages

      - name: Copiar archivos de docs a gh-pages
        run: cp -r docs/* gh-pages/

      - name: Desplegar en GitHub Pages
        if: always() && needs.test.result == 'success' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/DEV')
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./gh-pages

  notify:
    runs-on: ubuntu-latest
    name: Notificaciones a Slack
    needs: [test, deploy]
    steps:
      - name: Enviar notificación de éxito a Slack
        if: success()
        id: slack_success
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Despliegue exitoso para la rama ${{ github.ref }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Estado:* Exitoso\n*Rama:* ${{ github.ref }}\n*Autor:* ${{ github.event.head_commit.author.name }}\n*Comentario:* ${{ github.event.head_commit.message }}\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Ver commit>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Enviar notificación de fallo a Slack
        if: failure()
        id: slack_failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Fallo en el despliegue para la rama ${{ github.ref }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Estado:* Fallo\n*Rama:* ${{ github.ref }}\n*Autor:* ${{ github.event.head_commit.author.name }}\n*Comentario:* ${{ github.event.head_commit.message }}\n<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Ver commit>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
