name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Set up de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalacion de dependencias
        run: npm install

      - name: Crear directorio dist
        run: mkdir -p dist

      - name: Iniciar ESLint
        run: npx eslint src/**/*.js

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist

      - name: Deploy to GitHub Pages (Test Environment)
        if: github.ref == 'refs/heads/test'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: test
          publish_dir: ./dist

      - name: Notificaciones en Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI/CD Pipeline for branch ${{ github.ref }} completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
